/* Generated By:JavaCC: Do not edit this line. ReadconlistConstants.java */
package circuit.parser.conlist_ff;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ReadconlistConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IN = 6;
  /** RegularExpression Id. */
  int OUT = 7;
  /** RegularExpression Id. */
  int CLB = 8;
  /** RegularExpression Id. */
  int CON = 9;
  /** RegularExpression Id. */
  int PINLIST = 10;
  /** RegularExpression Id. */
  int SUBBLOCK = 11;
  /** RegularExpression Id. */
  int OPEN = 12;
  /** RegularExpression Id. */
  int Id = 13;
  /** RegularExpression Id. */
  int Idn = 14;
  /** RegularExpression Id. */
  int IdnId = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\".input\"",
    "\".output\"",
    "\".clb\"",
    "\".con\"",
    "\"pinlist:\"",
    "\"subblock:\"",
    "\"open\"",
    "<Id>",
    "<Idn>",
    "<IdnId>",
    "<NUMBER>",
  };

}
